const achievements = {
    "20": "Sap escriure amb lletra lligada",
    "50": "Sap llepar-se el colze",
    "100": "Sap saltar a corda",
    "135": "Sap dir 'Oh Long Johnson'",
    "180": "Sap bordar com un gos",
    "200": "Sap recitar un verset sobre la cadira",
    "250": "Ha après a dividir",
    "300": "Sap planxar camises",
    "400": "Sap fer gaspatxo",
    "500": "Sap liar porros amb una mà",
    "700": "Sap jugar al milikituli",
    "1000": "Se sap els Pokémons de la 1a generació per ordre",
    "1250": "S'ha tret el solo de Sweet Child o’mine",
    "1500": "Sap fer la declaració de la renda",
    "1800": "Sap fer truita de patates",
    "2000": "Sap parlar francès",
    "2400": "Sap fer parkour",
    "2500": "Sap conduir tractors",
    "2750": "Té un canal de YouTube",
    "3000": "Fa Patchwork",
    "3300": "És coach de Mindfullness",
    "3600": "Ha après que menjar kiwis regula el seu trànsit intestinal",
    "3800": "Té compte d’Amazon Prime",
    "4000": "Sap buscar coses al teletext",
    "4500": "Ha descobert una estrella",
    "5000": "Ha construït un bazooka",
    "5050": "Sap saltar a corda",
    "5300": "Ja té el passaport suís",
    "5500": "S’ha passat a l’hinduisme",
    "5900": "Quasi sempre fa perfects",
    "6000": "Sap comunicar-se amb silvo gomero",
    "6500": "Ha creat uns dibuixos animats sobre un humà robot que té una butxaca màgica",
    "7000": "Ha plantat un hort urbà",
    "7400": "Ha descobert que l'hermenèutica tel·lúrica incaica trastoca la peripatètica anotrètica de la filosofia aristotèl·lica per la iniquitat fàctica dels diàlegs socràtics no dogmàtics.",
    "7900": "Ha saldat tots els seus deutes amb Bizum",
    "8100": "Ha après a esbrinar el nombre de dies de cada mes amb els truc dels nudillus",
    "8500": "Ha anat a concursar a Pasapalabra",
    "8750": "Ha esbrinat la verdadera naturalesa de les meduses",
    "9000": "Ha viatjat en el temps i s’ha obert un compte de Fotolog",
    "9500": "Ha après a enrajolar",
    "9600": "És el rei menjant culs",
    "9700": "Ha aprovat les oposicions de notari",
    "10000": "Sap fer el pino puente",
    "11000": "S'ha fet una hipoteca",
    "12000": "S’ha comprat un patinet elèctric",
    "13000": "És enginyer industrial",
    "14000": "Sap descodificar el Canal+",
    "15000": "Sap fer cervesa artesana",
    "16000": "Sap recitar el primer capítol del Quijote canviant totes les vocals per la E",
    "17000": "Sap ballar linedance",
    "18000": "Sap passar d’euros a pessetes",
    "19000": "Ja té el passaport suís",
    "20000": "Ha guanyat el Nobel de la Pau",
    "21000": "Sap netejar l’historial del navegador",
    "22000": "Sap demanar tabac en italià",
    "23000": "S'ha fet un blanquejament anal",
    "24000": "Ha deixat de fumar",
    "25000": "És el president del club de fans de la Paulina Rubio",
    "26000": "S'ha estalviat el 50% d'una multa perquè ha pagat dins del termini",
    "27000": "Ha perdut la virginitat",
    "28000": "Ha creat una startup",
    "29000": "Ha comprat uns sanjacobos congelats",
    "30000": "Ha aconseguit superar l'addicció a aquest joc"
}
export default achievements